### ISSUE TITLE
Assertion Error

### ISSUE THREAD

**Issue by kanzaali** [chaoyuaw/pytorch-coviar#10]
@manzilzaheer @chaoyuaw 

hi,

Kindly please check this error and tell the possible reason and solution for it. I have run this on Server with 4 GPUs and attach is its screenshot. 
![3rd august](https://user-images.githubusercontent.com/33715985/43644519-0629b188-976a-11e8-965a-79b9ba501267.png)

**Comment by chaoyuaw** [comment]
It looks like you specify to use GPUs that don't exist.  For example, if you specify to use 4 GPUs for training, but only 2 GPUs are available, you see the error. I suggest use "nvidia-smi" command to see how many GPUs you have, and specify to train on those GPUs.

**Comment by kanzaali** [comment]
Thank you so much for your recommendations, Sir.
I am kept checking my GPUs by "nvidia-smi". In the screenshot, I have requested for 4 GPUs and I think they are working.....

![nvidia-smi](https://user-images.githubusercontent.com/33715985/43756450-bea1d7bc-9a4f-11e8-823a-42ec6f4603fa.png)

**Comment by chaoyuaw** [comment]
Glad to know that you get it working!

**Comment by kanzaali** [comment]
Sorry Sir, I mean GPUs are working but training is still giving same assertion error. I have only shown you that my GPUs are working.
