### ISSUE TITLE
codecs

### ISSUE THREAD

**Issue by Tylerjoe** [chaoyuaw/pytorch-coviar#11]
how long will you show other codecs ? Thanks

**Comment by chaoyuaw** [comment]
If you're referring to supporting, e.g. H.264, I don't have a very concrete plan yet. But if you want to go ahead and implement it, maybe you can start with using
https://github.com/chaoyuaw/pytorch-coviar/blob/master/data_loader/coviar_data_loader.c#L428
and
https://github.com/chaoyuaw/pytorch-coviar/blob/master/data_loader/coviar_data_loader.c#L440
for decoding H.264.

**Comment by RyanCV** [comment]
@chaoyuaw Do we only need to uncomment those lines (// pCodec = avcodec_find_decoder(AV_CODEC_ID_H264);  ) in coviar_data_loader.c in order to run H.264? Or any other places need to be modified? Thanks

**Comment by chaoyuaw** [comment]
H.264 uses B-frames, in addition to P- and I-frames. Our paper focuses on cases where only I-frames and P-frames are used. I think it's possible to modify the algorithm slightly (to accumulate MV and residuals in both directions) and make it work on B-frames, but we never really tried.

**Comment by Tylerjoe** [comment]
@chaoyuaw Thanks for your reply and patience
