### ISSUE TITLE
I want to ask the usage of crops and segments in test.py

### ISSUE THREAD

**Issue by Tylerjoe** [chaoyuaw/pytorch-coviar#12]
Thanks for your contribution!
I have a question about test.py
parser.add_argument('--test_segments', type=int, default=25)
parser.add_argument('--test-crops', type=int, default=10)
what is the usage of crops and segments?
Thanks!

**Comment by chaoyuaw** [comment]
--test-crops specifies how many crops per segment. The value should be 1 or 10. 1 means using only one center crop. 10 means using 5 crops for both (horizontal) flips. 

--test-segments specifies how many segments to sample in a "TSN (temporal segment network)". Many recent papers calculate the video-level prediction as the average of 25 frame-level predictions (the 25 frames are sampled uniformly in a video). So we follow and set the default as 25 here.

**Comment by Tylerjoe** [comment]
Thanks for your detailed answer
