### ISSUE TITLE
videos format

### ISSUE THREAD

**Issue by YIGAOYI** [chaoyuaw/pytorch-coviar#22]
I have videos in MP4 format, why do I need to transcode? Thank you.

**Comment by chaoyuaw** [comment]
To be safe, I think it's better to transcode. In the code we only support the format that has exactly 12 frames per GoP.

**Comment by YIGAOYI** [comment]
Will i change a lot about the codes of dataloader if  I want to use videos of h264 format? Thank you  for your reply.
