### ISSUE TITLE
/usr/bin/ld can't found -lavutil -lavcodec ...

### ISSUE THREAD

**Issue by FingerRec** [chaoyuaw/pytorch-coviar#3]
I follow the install guide.
as i run
`./install.sh`
the following problem happen:

/usr/bin/ld can't found -lavutil -lavcodec ...

i modify line6 in setup.py './ffmpeg/include/' , like 'opencv_install_path/include/'

looking forward to your reply

**Comment by FingerRec** [comment]
i have solved it

**Comment by jiarongqiu** [comment]
How did you solve it? I might face the same issue
