### ISSUE TITLE
Decoupled Model

### ISSUE THREAD

**Issue by kanzaali** [chaoyuaw/pytorch-coviar#32]
Good Day Respected @chaoyuaw,
Where are you calculating Decoupled Model in your code for breaking the dependency of Pframes?

**Comment by chaoyuaw** [comment]
Hi @kanza-ali , The "breaking the dependency" part happens in coviar_data_loader.c, which computes the accumulated motion vectors, and the accumulated resiual using the "breaking the dependency" technique. (The code might be a bit hard to read/parse though...)

**Comment by kanzaali** [comment]
Thank you so much @chaoyuaw for always replying my queries.
