### ISSUE TITLE
something wrong with  ./install.sh

### ISSUE THREAD

**Issue by zjyalice** [chaoyuaw/pytorch-coviar#33]
hello! when I execute install.sh，I meet some problems.
codes：
`static struct PyModuleDef coviarmodule = {
    PyModuleDef_HEAD_INIT,
    "coviar",   /* name of module */
    NULL,       /* module documentation, may be NULL */
    -1,         /* size of per-interpreter state of the module,
                 or -1 if the module keeps state in global variables. */
    CoviarMethods
};`
and the erroes are:
`error: variable 'coviarmodule' has initializer but incomplete type 
   static struct PyModuleDef coviarmodule = {
                      ^
error: variable 'PyModuleDef_HEAD_INIT' undeclared here (not in a function) 
   PyModuleDef_HEAD_INIT,
    ^
`
How to solve this problem?
Thanks!

**Comment by zjyalice** [comment]
I solve this problem！I run the codes in virtualenv enviroument and this environment does not install python3-dev, so the systemcannot find python.h.....
so, I install python-dev and this problem is solved.
And I have a queation. When I bash reencode.sh, does the data need to be unpacked from the tar.gz?

**Comment by chaoyuaw** [comment]
Yes, reencode.sh doesn't untar the files. It only performs re-encoding. Closing the issue for now, but please feel free to re-open if you have further questions. Thanks!
