### ISSUE TITLE
Decoding a video frame, given the previous frame, current motion vectors, and current residual image.

### ISSUE THREAD

**Issue by itoen220** [chaoyuaw/pytorch-coviar#37]
Assume we have _pos_target_=t, a reference frame at _pos_target_=t-1, and the motion vectors and residual image for the given _pos_target_=t. However, assume we don't have the original video file.

Given these constraints, I would like to reconstruct the frame at _pos_target_=t, as described in Equation 1 of your paper.

So far, I've tried decoding the frame at _pos_target_=t by: (1) creating a reference frame, which is just a copy of the t-1 frame; (2) performing motion compensation by copying 16x16 pixel blocks from the t-1 frame to the reference frame, based on the motion vectors; (3) adding the residual image to the motion-compensated reference frame.

This is the reference frame at _pos_target_=2:
![image](https://user-images.githubusercontent.com/45984837/50241434-547fcb00-037c-11e9-9d36-2dbc0ed9e375.png)

This is the result after step (1), for _pos_target_=3:
![image](https://user-images.githubusercontent.com/45984837/50258953-ead0e280-03b6-11e9-9d87-8995f2726ad1.png)

This is the result after step (2), for _pos_target_=3:
![image](https://user-images.githubusercontent.com/45984837/50258971-fb815880-03b6-11e9-8214-2bbe8e39095b.png)

The final result seems to have some compression artifacts, so I guess I'm not reconstructing the frame correctly. Is there a better way to do this (particularly, using ffmpeg)? Thanks!

**Comment by ffmpbgrnn** [comment]
Hi @itoen220 , do you have any updates on better reconstruction?

**Comment by AlexSte803** [comment]
@itoen220 Did you solve it? I have the same problem.

**Comment by shencuifeng** [comment]
> @itoen220 Did you solve it? I have the same problem.

did you reconstruct it?
