### ISSUE TITLE
ModuleNotFoundError: No module named 'coviar'

### ISSUE THREAD

**Issue by ZealACMer** [chaoyuaw/pytorch-coviar#39]
I execute sudo ./install.sh and get the following result:
![image](https://user-images.githubusercontent.com/16794553/50462873-13626900-09c3-11e9-8213-496ce454cc96.png)
Did I succeed? Then when I try the command for training, I got the following wrong error:
![image](https://user-images.githubusercontent.com/16794553/50462905-3d1b9000-09c3-11e9-8746-694f173320f0.png)
Did this mean the "./install.sh" didn't work successfully? I am a beginner, thank you very much for your guidance.

**Comment by ZealACMer** [comment]
I delete FFmpeg folder and start over again, this time when I tried to test whether I can import coviar successfully or not, I enter the python3.4 environment and type the command " import coviar", then I got the message as follows:
![image](https://user-images.githubusercontent.com/16794553/50469288-af519c00-09e6-11e9-97b3-319dbffaef9c.png)
How can I fix this problem, thank you very much.

**Comment by ZealACMer** [comment]
I start over again, this time I got another error message, the error happened when I import coviar same as before, the error information is shown as follows:
![image](https://user-images.githubusercontent.com/16794553/50471468-b16c2880-09ef-11e9-8620-b462618a3c15.png)
I sincerely hope you can help me to cope with this error, thank you very much.

**Comment by ZealACMer** [comment]
I have solved this problem, thank you very much.

**Comment by filipetrocadoferreira** [comment]
How?

**Comment by Esaada** [comment]
Please share with us!

**Comment by whwu95** [comment]
> I have solved this problem, thank you very much.

how? Please share with us! I meet the same problem "coviar.cpython-36m-x86_64-linux-gnu.so: undefined symbol: av_frame_alloc"

**Comment by Maruidear** [comment]
I have the same problem. Have you solved it?？
