### ISSUE TITLE
Encounter the problem "IndexError: invalid index of a 0-dim tensor. Use tensor.item() to convert a 0-dim tensor to a Python number", when I tried to train on HMDB51.

### ISSUE THREAD

**Issue by ZealACMer** [chaoyuaw/pytorch-coviar#40]
To be more specific, when I tried to use the following commands:
![image](https://user-images.githubusercontent.com/16794553/50500907-5427b400-0a8f-11e9-8bfc-834eb9f957b9.png)
I encountered the problem as shown in the following pic:
![image](https://user-images.githubusercontent.com/16794553/50500923-76213680-0a8f-11e9-800d-4dccd2a75e85.png)
I have not find the appropriate solution for this problem, can you help me? Thank you very much.

**Comment by ZealACMer** [comment]
When I tried to change loss.data[0] to loss.item(), but encountered another problem, error message is shown as follows:
![image](https://user-images.githubusercontent.com/16794553/50501545-e5992500-0a93-11e9-9ba9-863b0a5909e2.png)

How can I solve this, thank you very much.

**Comment by ZealACMer** [comment]
I have solved this problem， thank you every much.

**Comment by yellowjs0304** [comment]
@ZealACMer Hi, How did you resolve the problem? I encountered same issue.

**Comment by abhijeeetkumar** [comment]
What was the fix?
