### ISSUE TITLE
What does flush decoder mean?

### ISSUE THREAD

**Issue by Fangyh09** [chaoyuaw/pytorch-coviar#42]
https://github.com/chaoyuaw/pytorch-coviar/blob/4f0857a37ac9e283fcd9ebede950f33057d07eba/data_loader/coviar_data_loader.c#L366-L387
Hi, I wanna know what does flush decoder mean? Thanks!

**Comment by chaoyuaw** [comment]
Hi, the code was modified from other code bases (please see Acknowledgment), and I believe "Flush Decoder" is from the original example, and it has nothing to do with CoViAR algorithm. I'm sorry for the confusion. Please feel free to ignore it.
