### ISSUE TITLE
Please Help : ImportError: libavutil.so.56: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Esaada** [chaoyuaw/pytorch-coviar#52]
I after all the steps (except make clean) I got this error:
"ImportError: libavutil.so.56: cannot open shared object file: No such file or directory"
when trying to do "import coviar" or "from coviar import load"..
Any Idea how do I fill this gap?!

**Comment by noirblack** [comment]
add ${FFMPEG_INSTALL_PATH}/lib/ to $LD_LIBRARY_PATH
