### ISSUE TITLE
What does it need to support kinetics dataset?

### ISSUE THREAD

**Issue by Esaada** [chaoyuaw/pytorch-coviar#53]
Hi, I saw that this repo is not supporting kinetics, and  I wonder if you may help me understand what's missing?
Changes needed:
1. I saw that there is no reencode.sh script for kinetics - will do.
2. Does data_loader.c need to be changed?
3.Does Dataset.py needs to be changed?

Anything else?
Thanks!

**Comment by chaoyuaw** [comment]
Hi, I think what we need is a reencode.sh to re-encode kinetics into the mpeg4 format we support. I don't think we need to change any c++ code. We'll also need to create a list under data/datalists/ for kinetics. And it seems the current dataset.py might not need additional changes (at least no big changes) to support Kinetics.

**Comment by Esaada** [comment]
That's great news, Thanks
