### ISSUE TITLE
How to compute FPS of one video 

### ISSUE THREAD

**Issue by luyao777** [chaoyuaw/pytorch-coviar#58]
Hi, I want to ask how do you compute the fps of one video during testing phase. Is the nunber of frames of one video is 25 or is the true frames of the video?

Thank you very much. :grin:

**Comment by chaoyuaw** [comment]
I'm not sure if I understand your question correctly, but training and testing videos are created in the same way. That is, we didn't make the testing video exactly 25 frames. We sample 25 frames from the video during testing (https://github.com/chaoyuaw/pytorch-coviar/blob/master/test.py).

**Comment by luyao777** [comment]
Thanks ! :yum:
