### ISSUE TITLE
fatal: reference is not a tree: 74c6a6d3735f79671b177a0e0c6f2db696c2a6d2

### ISSUE THREAD

**Issue by Maruidear** [chaoyuaw/pytorch-coviar#79]
When I execute "git checkout 74c6a6d3735f79671b177a0e0c6f2db696c2a6d2", I encounter this problem.What should I do?

**Comment by Maruidear** [comment]
![image](https://user-images.githubusercontent.com/49900763/70106234-ff68c200-167d-11ea-970e-a07eefeb65dd.png)

**Comment by ghost** [comment]
Same question with me, did you solve this problem?
