### ISSUE TITLE
numpy issue during ./install.sh

### ISSUE THREAD

**Issue by srikar2097** [chaoyuaw/pytorch-coviar#8]
thank you for your lovely paper. was trying to get your code to work. We are using amazon AMI and got FFmpeg compiled and using python3 an pytorch. when trying to run ./install.sh with the ffmpeg path we get the following GCC error. Any idea of how to resolve this? it says Numpy decprecated API. What version of Numpy was used?

<img width="1274" alt="screen shot 2018-07-27 at 12 44 52 am" src="https://user-images.githubusercontent.com/391500/43308576-df6e5992-9136-11e8-9761-68f4fbc62bae.png">

we also followed steps in other issues - https://github.com/chaoyuaw/pytorch-coviar/issues/6 and https://github.com/chaoyuaw/pytorch-coviar/issues/5 but the error still persists.

**Comment by srikar2097** [comment]
got this working. issue closed.

**Comment by srikar2097** [comment]
To help someone else in future: At compile, the correct .h files were not in the path. including them solved it.

**Comment by chaoyuaw** [comment]
Hi @srikar2097 , sorry for the late reply. Glad that you solved it!

**Comment by fengfan028** [comment]
> To help someone else in future: At compile, the correct .h files were not in the path. including them solved it.

how to include them?

**Comment by Dreamer312** [comment]
Got the same problem, where are .h files.
