### ISSUE TITLE
How to reconstruct the frame?

### ISSUE THREAD

**Issue by zhipeng-fan** [chaoyuaw/pytorch-coviar#88]
Hi! How would I reconstruct the frame using the motion vector, residual, and the initial I frame? I tried to warp the initial I frame of. the GOP according to the accumulated motion vector and then add the residual, but the results look weird somehow.

**Comment by zhipeng-fan** [comment]
Problem solved. Using the MV wrongly.

**Comment by AlexSte803** [comment]
@zhipeng-fan  how did you reconstruct the frame? I also tried to reconstruct the frame, but my results show some strange artifacts.

**Comment by Dreamer312** [comment]
So, 怎么玩

**Comment by shencuifeng** [comment]
> @zhipeng-fan how did you reconstruct the frame? I also tried to reconstruct the frame, but my results show some strange artifacts.

Hi, did you successfully reconstruct the frame?
