### ISSUE TITLE
Transfer learning using Coviar

### ISSUE THREAD

**Issue by srikar2097** [chaoyuaw/pytorch-coviar#9]
was wondering what your thoughts was on transfer learning in videos by coviar. I know some experiments were done by [Karpathy et. al](https://static.googleusercontent.com/media/research.google.com/en//pubs/archive/42455.pdf) and few other works tried a few experiments (B. Zhang L et. al). Was any transfer learning experiments done with the coviar?

**Comment by chaoyuaw** [comment]
Hi @srikar2097 , thanks for your question. We haven't studied transfer learning setting with  CoViAR yet. I think it's an interesting direction.
